<a href="https://colab.research.google.com/github/vivianecristino2/An-Undying-Loop/blob/master/Golden.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Explanation:**
### Load the CSV file: We load the data from the original CSV file.

1.  Load the CSV file: We load the data from the original CSV file.
2.  Drop unnecessary columns: We remove the columns that are not needed for the analysis.
3. Define country categories: We create a new column Country_Category that
categorizes the countries as European Union, BRICS, UK, or N/A.

4. Calculate the transaction value in tons: We add a new column Trade_Value_Tons that converts the Fobvalue to tons by dividing by 56 million.

5. Save and display the DataFrame: We save the modified DataFrame to a new CSV file and display the first few rows of the resulting DataFrame.

## Make sure to adjust the file paths as necessary for your environment. This code will:


*   Load the original CSV file.
*   Remove unnecessary columns.
*   Create a new Country_Category column to categorize countries.
*   Add a Trade_Value_Tons column to convert trade values to tons.
*   Save the modified DataFrame to a new CSV file and display the first few rows.

In [1]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.25.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [2]:
import pandas as pd

# importando o arquivo

In [57]:


# Tentar ler o arquivo CSV com a codificação 'ISO-8859-1'
try:
    Golden = pd.read_csv("TradeDataGolden.csv", sep=',', encoding='ISO-8859-1')
    print(Golden.head())  # Exibir as primeiras linhas do DataFrame para ver se a leitura foi bem-sucedida
except FileNotFoundError:
    print("Erro: Arquivo não encontrado. Verifique o nome e o caminho do arquivo.")
except pd.errors.ParserError:
    print("Erro: Problema ao analisar o arquivo. Verifique o separador e a estrutura do arquivo.")
except Exception as e:
    print(f"Erro inesperado: {e}")

# Exibir o DataFrame lido
Golden

  TypeCode FreqCode  RefPeriodId  RefYear  RefMonth  Period  ReporterCode  \
0        C        A     20170101     2017        52    2017           288
1        C        A     20170101     2017        52    2017           288
2        C        A     20170101     2017        52    2017           288
3        C        A     20170101     2017        52    2017           288
4        C        A     20170101     2017        52    2017           288

  ReporterISO ReporterDesc FlowCode  ... IsNetWgtEstimated  GrossWgt  \
0         GHA        Ghana        X  ...              True       NaN
1         GHA        Ghana        X  ...             False       NaN
2         GHA        Ghana        X  ...             False       NaN
3         GHA        Ghana        X  ...             False       NaN
4         GHA        Ghana        X  ...             False       NaN

  IsGrossWgtEstimated Cifvalue      Fobvalue  PrimaryValue  \
0               False      NaN  5.858281e+09  5.858281e+09
1               False      NaN  1.103010e+06  1.103010e+06
2               False      NaN  9.274560e+05  9.274560e+05
3               False      NaN  4.926127e+03  4.926127e+03
4               False      NaN  1.940124e+04  1.940124e+04

  LegacyEstimationFlag IsReported IsAggregate  Unnamed: 47
0                    0      False        True          NaN
1                    0      False        True          NaN
2                    0      False        True          NaN
3                    0      False        True          NaN
4                    0      False        True          NaN

[5 rows x 48 columns]

,TypeCode,FreqCode,RefPeriodId,RefYear,RefMonth,Period,ReporterCode,ReporterISO,ReporterDesc,FlowCode,...,IsNetWgtEstimated,GrossWgt,IsGrossWgtEstimated,Cifvalue,Fobvalue,PrimaryValue,LegacyEstimationFlag,IsReported,IsAggregate,Unnamed: 47
0,C,A,20170101,2017,52,2017,288,GHA,Ghana,X,...,True,NaN,False,NaN,5.858281e+09,5.858281e+09,0,False,True,NaN
1,C,A,20170101,2017,52,2017,288,GHA,Ghana,X,...,False,NaN,False,NaN,1.103010e+06,1.103010e+06,0,False,True,NaN
2,C,A,20170101,2017,52,2017,288,GHA,Ghana,X,...,False,NaN,False,NaN,9.274560e+05,9.274560e+05,0,False,True,NaN
3,C,A,20170101,2017,52,2017,288,GHA,Ghana,X,...,False,NaN,False,NaN,4.926127e+03,4.926127e+03,0,False,True,NaN
4,C,A,20170101,2017,52,2017,288,GHA,Ghana,X,...,False,NaN,False,NaN,1.940124e+04,1.940124e+04,0,False,True,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
422,C,A,20230101,2023,52,2023,710,ZAF,South Africa,X,...,False,0.0,False,NaN,2.274770e+02,2.274770e+02,0,False,True,NaN
423,C,A,20230101,2023,52,2023,710,ZAF,South Africa,X,...,False,0.0,False,NaN,6.290623e+09,6.290623e+09,0,False,True,NaN
424,C,A,20230101,2023,52,2023,710,ZAF,South Africa,X,...,False,0.0,False,NaN,1.078600e+01,1.078600e+01,0,False,True,NaN
425,C,A,20230101,2023,52,2023,710,ZAF,South Africa,X,...,True,0.0,False,NaN,3.746183e+03,3.746183e+03,6,False,True,NaN
426,C,A,20230101,2023,52,2023,710,ZAF,South Africa,X,...,False,0.0,False,NaN,6.290619e+09,6.290619e+09,0,False,True,NaN

In [59]:
ghana_data = Golden[Golden['ReporterDesc'] == 'Ghana']
print(ghana_data.head())

  TypeCode FreqCode  RefPeriodId  RefYear  RefMonth  Period  ReporterCode  \
0        C        A     20170101     2017        52    2017           288
1        C        A     20170101     2017        52    2017           288
2        C        A     20170101     2017        52    2017           288
3        C        A     20170101     2017        52    2017           288
4        C        A     20170101     2017        52    2017           288

  ReporterISO ReporterDesc FlowCode  ... IsNetWgtEstimated  GrossWgt  \
0         GHA        Ghana        X  ...              True       NaN
1         GHA        Ghana        X  ...             False       NaN
2         GHA        Ghana        X  ...             False       NaN
3         GHA        Ghana        X  ...             False       NaN
4         GHA        Ghana        X  ...             False       NaN

  IsGrossWgtEstimated Cifvalue      Fobvalue  PrimaryValue  \
0               False      NaN  5.858281e+09  5.858281e+09
1               False      NaN  1.103010e+06  1.103010e+06
2               False      NaN  9.274560e+05  9.274560e+05
3               False      NaN  4.926127e+03  4.926127e+03
4               False      NaN  1.940124e+04  1.940124e+04

  LegacyEstimationFlag IsReported IsAggregate  Unnamed: 47
0                    0      False        True          NaN
1                    0      False        True          NaN
2                    0      False        True          NaN
3                    0      False        True          NaN
4                    0      False        True          NaN

[5 rows x 48 columns]

In [66]:
import pandas as pd

# Carregar o arquivo CSV
file_path = '/content/TradeDataGolden.csv'  # Verifique se o caminho e o nome do arquivo estão corretos
ghana_data = pd.read_csv(file_path, encoding='latin1')

# Lista de colunas a serem excluídas
columns_to_drop = [
    'Unnamed: 47', 'GrossWgt', 'TypeCode', 'FreqCode', 'RefMonth', 'FlowCode',
    'Partner2ISO', 'Partner2Desc', 'ClassificationSearchCode', 'IsOriginalClassification',
    'CustomsCode', 'CustomsDesc', 'MosCode', 'MotCode', 'MotDesc', 'IsAltQtyEstimated', 'GrossWgt',
    'AltQtyUnitAbbr', 'IsGrossWgtEstimated', 'Cifvalue','LegacyEstimationFlag',
]

# Excluir as colunas
data_reduced = ghana_data.drop(columns=columns_to_drop)

# Salvar o novo DataFrame reduzido em um novo arquivo CSV
output_file_path = '/content/TradeDataGolden_Reduced.csv'  # Verifique se o caminho de saída está correto
data_reduced.to_csv(output_file_path, index=False)

# Exibir as primeiras linhas do DataFrame reduzido
print(data_reduced.head())

   RefPeriodId  RefYear  Period  ReporterCode ReporterISO ReporterDesc  \
0     20170101     2017    2017           288         GHA        Ghana
1     20170101     2017    2017           288         GHA        Ghana
2     20170101     2017    2017           288         GHA        Ghana
3     20170101     2017    2017           288         GHA        Ghana
4     20170101     2017    2017           288         GHA        Ghana

  FlowDesc  PartnerCode PartnerISO PartnerDesc  ...         Qty  \
0   Export            0        W00       World  ...  197809.923
1   Export           36        AUS   Australia  ...      28.140
2   Export           56        BEL     Belgium  ...      20.740
3   Export           76        BRA      Brazil  ...       0.590
4   Export          124        CAN      Canada  ...       0.460

  IsQtyEstimated  AltQtyUnitCode AltQty  NetWgt  IsNetWgtEstimated  \
0           True              -1   0.00     NaN               True
1          False               8  28.14   28.14              False
2          False               8  20.74   20.74              False
3          False               8   0.59    0.59              False
4          False               8   0.46    0.46              False

       Fobvalue  PrimaryValue  IsReported  IsAggregate
0  5.858281e+09  5.858281e+09       False         True
1  1.103010e+06  1.103010e+06       False         True
2  9.274560e+05  9.274560e+05       False         True
3  4.926127e+03  4.926127e+03       False         True
4  1.940124e+04  1.940124e+04       False         True

[5 rows x 28 columns]

In [67]:
# Calculate total exports and imports
total_exports = ghana_data[ghana_data['FlowDesc'] == 'Export']['PrimaryValue'].sum()
total_imports = ghana_data[ghana_data['FlowDesc'] == 'Import']['PrimaryValue'].sum()

print(f'Total Exports: {total_exports}')
print(f'Total Imports: {total_imports}')

Total Exports: 312257171111.00397
Total Imports: 0.0

In [68]:
# Identify top trading partners
top_partners = ghana_data['PartnerDesc'].value_counts().head(10)
print('Top Trading Partners:')
print(top_partners)

Top Trading Partners:
PartnerDesc
World                   44
Namibia                 23
India                   19
United Arab Emirates    17
Eswatini                16
Türkiye                 15
Botswana                15
China, Hong Kong SAR    15
Areas, nes              14
Rep. of Korea           12
Name: count, dtype: int64

In [69]:
# Identify top exported and imported products
top_exported_products = ghana_data[ghana_data['FlowDesc'] == 'Export']['CmdDesc'].value_counts().head(10)
top_imported_products = ghana_data[ghana_data['FlowDesc'] == 'Import']['CmdDesc'].value_counts().head(10)

print('Top Exported Products:')
print(top_exported_products)
print('Top Imported Products:')
print(top_imported_products)

Top Exported Products:
CmdDesc
Gold (including gold plated with platinum) unwrought or in semi-manufactured forms, or in powder form    182
Metals; gold, semi-manufactured                                                                          168
Metals; gold, non-monetary, unwrought (but not powder)                                                    60
Metals; gold, non-monetary, powder                                                                        17
Name: count, dtype: int64
Top Imported Products:
Series([], Name: count, dtype: int64)

In [70]:


# Definir os países da União Europeia, BRICS e UK
eu_countries = [
    'Austria', 'Belgium', 'Bulgaria', 'Croatia', 'Cyprus', 'Czech Republic', 'Denmark', 'Estonia', 'Finland', 'France',
    'Germany', 'Greece', 'Hungary', 'Ireland', 'Italy', 'Latvia', 'Lithuania', 'Luxembourg', 'Malta', 'Netherlands',
    'Poland', 'Portugal', 'Romania', 'Slovakia', 'Slovenia', 'Spain', 'Sweden'
]
brics_countries = ['Brazil', 'Russia', 'India', 'China', 'South Africa']
uk_countries = ['United Kingdom']

# Criar a nova coluna com base nas condições
def categorize_country(country):
    if country in eu_countries:
        return 'União Europeia'
    elif country in brics_countries:
        return 'BRICS'
    elif country in uk_countries:
        return 'UK'
    else:
        return 'N/A'

data_reduced['Country_Category'] = data_reduced['PartnerDesc'].apply(categorize_country)

# Salvar o DataFrame modificado em um novo arquivo CSV
output_file_path = '/content/TradeDataGolden_Reduced_with_Country_Category.csv'  # Verifique se o caminho de saída está correto
data_reduced.to_csv(output_file_path, index=False)

# Exibir as primeiras linhas do DataFrame modificado
print(data_reduced.head())

   RefPeriodId  RefYear  Period  ReporterCode ReporterISO ReporterDesc  \
0     20170101     2017    2017           288         GHA        Ghana
1     20170101     2017    2017           288         GHA        Ghana
2     20170101     2017    2017           288         GHA        Ghana
3     20170101     2017    2017           288         GHA        Ghana
4     20170101     2017    2017           288         GHA        Ghana

  FlowDesc  PartnerCode PartnerISO PartnerDesc  ...  IsQtyEstimated  \
0   Export            0        W00       World  ...            True
1   Export           36        AUS   Australia  ...           False
2   Export           56        BEL     Belgium  ...           False
3   Export           76        BRA      Brazil  ...           False
4   Export          124        CAN      Canada  ...           False

  AltQtyUnitCode  AltQty NetWgt  IsNetWgtEstimated      Fobvalue  \
0             -1    0.00    NaN               True  5.858281e+09
1              8   28.14  28.14              False  1.103010e+06
2              8   20.74  20.74              False  9.274560e+05
3              8    0.59   0.59              False  4.926127e+03
4              8    0.46   0.46              False  1.940124e+04

   PrimaryValue IsReported  IsAggregate  Country_Category
0  5.858281e+09      False         True               N/A
1  1.103010e+06      False         True               N/A
2  9.274560e+05      False         True    União Europeia
3  4.926127e+03      False         True             BRICS
4  1.940124e+04      False         True               N/A

[5 rows x 29 columns]

In [75]:
# Exibir as primeiras 20 linhas do DataFrame
print(data_reduced.iloc[:20])

    RefPeriodId  RefYear  Period  ReporterCode ReporterISO ReporterDesc  \
0      20170101     2017    2017           288         GHA        Ghana
1      20170101     2017    2017           288         GHA        Ghana
2      20170101     2017    2017           288         GHA        Ghana
3      20170101     2017    2017           288         GHA        Ghana
4      20170101     2017    2017           288         GHA        Ghana
5      20170101     2017    2017           288         GHA        Ghana
6      20170101     2017    2017           288         GHA        Ghana
7      20170101     2017    2017           288         GHA        Ghana
8      20170101     2017    2017           288         GHA        Ghana
9      20170101     2017    2017           288         GHA        Ghana
10     20170101     2017    2017           288         GHA        Ghana
11     20170101     2017    2017           288         GHA        Ghana
12     20170101     2017    2017           288         GHA        Ghana
13     20170101     2017    2017           288         GHA        Ghana
14     20170101     2017    2017           288         GHA        Ghana
15     20170101     2017    2017           288         GHA        Ghana
16     20170101     2017    2017           288         GHA        Ghana
17     20170101     2017    2017           288         GHA        Ghana
18     20170101     2017    2017           288         GHA        Ghana
19     20170101     2017    2017           288         GHA        Ghana

   FlowDesc  PartnerCode PartnerISO           PartnerDesc  ...  \
0    Export            0        W00                 World  ...
1    Export           36        AUS             Australia  ...
2    Export           56        BEL               Belgium  ...
3    Export           76        BRA                Brazil  ...
4    Export          124        CAN                Canada  ...
5    Export          276        DEU               Germany  ...
6    Export          344        HKG  China, Hong Kong SAR  ...
7    Export          380        ITA                 Italy  ...
8    Export          392        JPN                 Japan  ...
9    Export          410        KOR         Rep. of Korea  ...
10   Export          422        LBN               Lebanon  ...
11   Export          458        MYS              Malaysia  ...
12   Export          490        S19       Other Asia, nes  ...
13   Export          528        NLD           Netherlands  ...
14   Export          586        PAK              Pakistan  ...
15   Export          620        PRT              Portugal  ...
16   Export          634        QAT                 Qatar  ...
17   Export          699        IND                 India  ...
18   Export          702        SGP             Singapore  ...
19   Export          710        ZAF          South Africa  ...

    IsQtyEstimated AltQtyUnitCode     AltQty     NetWgt  IsNetWgtEstimated  \
0             True             -1       0.00        NaN               True
1            False              8      28.14      28.14              False
2            False              8      20.74      20.74              False
3            False              8       0.59       0.59              False
4            False              8       0.46       0.46              False
5            False              8       5.43       5.43              False
6            False              8    1247.50    1247.50              False
7            False              8      13.47      13.47              False
8            False              8      23.12      23.12              False
9            False              8      51.87      51.87              False
10           False              8     574.61     574.61              False
11           False              8       0.90       0.90              False
12           False              8       0.94       0.94              False
13           False              8       1.00       1.00              False
14            True             -1       0.00        NaN               True
15           False              8       0.70       0.70              False
16           False              8       1.80       1.80              False
17           False              8  100504.94  100504.94              False
18           False              8      12.87      12.87              False
19           False              8   24933.80   24933.80              False

        Fobvalue  PrimaryValue IsReported  IsAggregate  Country_Category
0   5.858281e+09  5.858281e+09      False         True               N/A
1   1.103010e+06  1.103010e+06      False         True               N/A
2   9.274560e+05  9.274560e+05      False         True    União Europeia
3   4.926127e+03  4.926127e+03      False         True             BRICS
4   1.940124e+04  1.940124e+04      False         True               N/A
5   1.954021e+05  1.954021e+05      False         True    União Europeia
6   5.127684e+07  5.127684e+07      False         True               N/A
7   5.814523e+05  5.814523e+05      False         True    União Europeia
8   9.958101e+05  9.958101e+05      False         True               N/A
9   2.196377e+06  2.196377e+06      False         True               N/A
10  2.326810e+07  2.326810e+07      False         True               N/A
11  3.825357e+04  3.825357e+04      False         True               N/A
12  3.754260e+04  3.754260e+04      False         True               N/A
13  4.125595e+04  4.125595e+04      False         True    União Europeia
14  4.105327e+06  4.105327e+06      False         True               N/A
15  2.583098e+04  2.583098e+04      False         True    União Europeia
16  7.790545e+04  7.790545e+04      False         True               N/A
17  2.535782e+09  2.535782e+09      False         True             BRICS
18  5.382427e+05  5.382427e+05      False         True               N/A
19  8.517454e+08  8.517454e+08      False         True             BRICS

[20 rows x 29 columns]

In [77]:
# Calcular a nova coluna para converter trade value em toneladas
data_reduced['Trade_Value_Tons'] = data_reduced['Fobvalue'] / 56_000_000

# Salvar o DataFrame modificado em um novo arquivo CSV
output_file_path = '/content/TradeDataGolden_Reduced_with_Country_Category_and_Trade_Value_Tons.csv'  # Verifique se o caminho de saída está correto
data_reduced.to_csv(output_file_path, index=False)

# Exibir as primeiras linhas do DataFrame modificado
print(data_reduced.head(20))

    RefPeriodId  RefYear  Period  ReporterCode ReporterISO ReporterDesc  \
0      20170101     2017    2017           288         GHA        Ghana
1      20170101     2017    2017           288         GHA        Ghana
2      20170101     2017    2017           288         GHA        Ghana
3      20170101     2017    2017           288         GHA        Ghana
4      20170101     2017    2017           288         GHA        Ghana
5      20170101     2017    2017           288         GHA        Ghana
6      20170101     2017    2017           288         GHA        Ghana
7      20170101     2017    2017           288         GHA        Ghana
8      20170101     2017    2017           288         GHA        Ghana
9      20170101     2017    2017           288         GHA        Ghana
10     20170101     2017    2017           288         GHA        Ghana
11     20170101     2017    2017           288         GHA        Ghana
12     20170101     2017    2017           288         GHA        Ghana
13     20170101     2017    2017           288         GHA        Ghana
14     20170101     2017    2017           288         GHA        Ghana
15     20170101     2017    2017           288         GHA        Ghana
16     20170101     2017    2017           288         GHA        Ghana
17     20170101     2017    2017           288         GHA        Ghana
18     20170101     2017    2017           288         GHA        Ghana
19     20170101     2017    2017           288         GHA        Ghana

   FlowDesc  PartnerCode PartnerISO           PartnerDesc  ...  \
0    Export            0        W00                 World  ...
1    Export           36        AUS             Australia  ...
2    Export           56        BEL               Belgium  ...
3    Export           76        BRA                Brazil  ...
4    Export          124        CAN                Canada  ...
5    Export          276        DEU               Germany  ...
6    Export          344        HKG  China, Hong Kong SAR  ...
7    Export          380        ITA                 Italy  ...
8    Export          392        JPN                 Japan  ...
9    Export          410        KOR         Rep. of Korea  ...
10   Export          422        LBN               Lebanon  ...
11   Export          458        MYS              Malaysia  ...
12   Export          490        S19       Other Asia, nes  ...
13   Export          528        NLD           Netherlands  ...
14   Export          586        PAK              Pakistan  ...
15   Export          620        PRT              Portugal  ...
16   Export          634        QAT                 Qatar  ...
17   Export          699        IND                 India  ...
18   Export          702        SGP             Singapore  ...
19   Export          710        ZAF          South Africa  ...

    AltQtyUnitCode     AltQty     NetWgt IsNetWgtEstimated      Fobvalue  \
0               -1       0.00        NaN              True  5.858281e+09
1                8      28.14      28.14             False  1.103010e+06
2                8      20.74      20.74             False  9.274560e+05
3                8       0.59       0.59             False  4.926127e+03
4                8       0.46       0.46             False  1.940124e+04
5                8       5.43       5.43             False  1.954021e+05
6                8    1247.50    1247.50             False  5.127684e+07
7                8      13.47      13.47             False  5.814523e+05
8                8      23.12      23.12             False  9.958101e+05
9                8      51.87      51.87             False  2.196377e+06
10               8     574.61     574.61             False  2.326810e+07
11               8       0.90       0.90             False  3.825357e+04
12               8       0.94       0.94             False  3.754260e+04
13               8       1.00       1.00             False  4.125595e+04
14              -1       0.00        NaN              True  4.105327e+06
15               8       0.70       0.70             False  2.583098e+04
16               8       1.80       1.80             False  7.790545e+04
17               8  100504.94  100504.94             False  2.535782e+09
18               8      12.87      12.87             False  5.382427e+05
19               8   24933.80   24933.80             False  8.517454e+08

    PrimaryValue  IsReported IsAggregate  Country_Category  Trade_Value_Tons
0   5.858281e+09       False        True               N/A        104.612160
1   1.103010e+06       False        True               N/A          0.019697
2   9.274560e+05       False        True    União Europeia          0.016562
3   4.926127e+03       False        True             BRICS          0.000088
4   1.940124e+04       False        True               N/A          0.000346
5   1.954021e+05       False        True    União Europeia          0.003489
6   5.127684e+07       False        True               N/A          0.915658
7   5.814523e+05       False        True    União Europeia          0.010383
8   9.958101e+05       False        True               N/A          0.017782
9   2.196377e+06       False        True               N/A          0.039221
10  2.326810e+07       False        True               N/A          0.415502
11  3.825357e+04       False        True               N/A          0.000683
12  3.754260e+04       False        True               N/A          0.000670
13  4.125595e+04       False        True    União Europeia          0.000737
14  4.105327e+06       False        True               N/A          0.073309
15  2.583098e+04       False        True    União Europeia          0.000461
16  7.790545e+04       False        True               N/A          0.001391
17  2.535782e+09       False        True             BRICS         45.281814
18  5.382427e+05       False        True               N/A          0.009611
19  8.517454e+08       False        True             BRICS         15.209740

[20 rows x 30 columns]